service: serverless-sub-routing

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  timeout: 60
  region: eu-west-1
  environment:
    USERS_DDB_TABLE_NAME: users-local
    DDB_OFFLINE_ENDPOINT: http://localhost:8000
    AWS_ACCESS_KEY_ID: accessKeyId
    AWS_SECRET_ACCESS_KEY: secretAccessKey

functions:
  deleteUser:
    handler: dist/functions/delete-user/index.handler
    events:
      - http:
          path: /users/{staffNumber}
          method: DELETE
  app:
    handler: dist/src/proxy/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any

custom:
  dynamodb:
    stages:
      - test
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:provider.environment.USERS_DDB_TABLE_NAME}
            sources: [./tests/test-data/dynamo-seed-users.json]

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: staffNumber
            AttributeType: S
        KeySchema:
          - AttributeName: staffNumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline
