name: Update Dependencies

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  schedule:
    # Runs at 07:00 on the first day of every month
    - cron: '0 7 1 * *'
  workflow_dispatch:
    inputs:
      pat:
        description: 'Is a Personal Access Token (PAT) required to install dependencies?'
        type: boolean
        default: false
        required: false
      updateType:
        description: 'Update Type (major, minor, patch)'
        required: true
        default: 'minor'
        type: 'choice'
        options:
          - major
          - minor
          - patch

jobs:
  update:
    uses: dvsa/appdev-github-actions/.github/workflows/update-dependencies.yaml@main
    with:
      update-type: ${{ inputs.updateType }}
    secrets:
      inherit: true
