name: Update Dependencies

on:
  schedule:
    # Runs at 07:00 on the first day of every month
    - cron: '0 7 1 * *'
  workflow_dispatch:
    updateType:
      description: 'Update Type (major, minor, patch)'
      required: true
      default: 'minor'
      choices:
        - major
        - minor
        - patch

jobs:
  update:
    uses: dvsa/appdev-github-actions/.github/workflows/update-dependencies.yaml@main
    with:
      update-type: ${{ inputs.updateType }}
    secrets:
      inherit: true
